# Generated by Django 5.0.1 on 2024-02-24 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModalsDateBase', '0009_remove_post_author_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content_post',
        ),
        migrations.AddField(
            model_name='post',
            name='content_post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_category', to='ModalsDateBase.catigory'),
        ),
    ]
