# Generated by Django 5.0.1 on 2024-02-27 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ModalsDateBase', '0004_remove_post_author_alter_post_content_post_and_more'),
        ('ModalsDateBase', '0010_remove_post_content_post_post_content_post'),
    ]

    operations = [
    ]
